### ISSUE TITLE
Support astroid > 2

### ISSUE THREAD

**Issue by chocoelho** [landscapeio/pylint-common#9]

**Comment by costastf** [comment]
The current version breaks many things with python 2.7 as the dependency to pylint-plugin-utils which is pinned to 0.2.6 drops support for python 2.7. This essentially breaks everything up to prospector which uses this as a dependency for python 2.7. Astroid version 2 is also not compatible with python 2.7.

**Comment by carlio** [comment]
Closing this as pylint-common is no longer used by prospector and I doubt it was used anywhere else.
